### ISSUE TITLE
meta/code-of-conduct

### ISSUE THREAD

**Issue by sadasant** [berserktech/ideas#11]
Por ahora este repositorio y nuestra comunidad estarán asociados al Contributor Covenant, ya que viene como una de las dos opciones que ofrece GitHub _por defecto_. Por esa misma razón, queda aquí abierta la discusión sobre si deberíamos permanecer con ese código de conducta, o cambiarlo.

**Comment by jobliz** [comment]
Si bien estoy de acuerdo en que tener un código de conducta es conveniente para una comunidad, considero importante resaltar que el Contributor's Covenant es utilizado por sus adeptos para obtener relevancia política a nivel personal, utilizando la idea de mejorar las interacciones interpersonales en las comunidades como un medio para tal fin. Como un ejemplo puede verse [la larga discusión en la lista de correo de Ruby](https://bugs.ruby-lang.org/issues/12004), tras la cual Matsumoto desarrolló un [código de conducta minimalista](https://www.ruby-lang.org/en/conduct/).

La diferencia allí es clara: Matsumoto quiere un código de conducta con principios sencillos que todos puedan recordar con el menor esfuerzo posible y que sea suficiente para la buena convivencia, para de ese modo disponer de más atención humana en los asuntos organizativos de la comunidad y los problemas técnicos, mientras que la gente asociada con el Contributor's Covenant desea desviar la mayor cantidad de atención posible de la comunidad hacia el código de conducta y su ideología política.

A nivel personal, quisiera que adoptáramos el código de Conducta de Ruby.

**Comment by sadasant** [comment]
@jobliz usaré ese
